### ISSUE TITLE
Data attribute instead of class

### ISSUE THREAD

**Issue by tomjn** [tuupola/jquery_chained#20]
The values I need to chain can have spaces in them, and css classes can impact styling. Would it be possible to add support for data attributes as a mechanism?

**Comment by Aeon** [comment]
any update?

**Comment by tuupola** [comment]
See https://github.com/tuupola/jquery_chained/commit/a3bfdbc2b895842e495a75bbeba1b915acd6f9cb. Will be released in 2.0.0.
