### ISSUE TITLE
selects options preselection

### ISSUE THREAD

**Issue by Serg10** [tuupola/jquery_chained#39]
Hi!

I want to preselect selects option, for this I created a function in js that puts the selected = "selected" attribute to the options I need, but do not seem to work with the plugin.

Thank You!

**Comment by tuupola** [comment]
Use [$.val()](http://api.jquery.com/val/) for setting select values.

**Comment by Serg10** [comment]
I tried, but it only works in Firefox and sometimes ... I get the same result quecon other solutions I've tried

Y tried with: $.val() , $.attr(), $.prop

**Comment by tuupola** [comment]
You can also preselect options using the JSON as described in [documentation](http://www.appelsiini.net/projects/chained).
