### ISSUE TITLE
Multiple instances in a form

### ISSUE THREAD

**Issue by blyleven** [tuupola/jquery_chained#45]
Hi there, 

Is it possible to have a form with 2 selectboxes, using this plugin while they're both an array? 

Like:
`<select name="category[]"><options here></select>
<select name="product[]"><options here></select>`

Hope there is a way to get this working. So far only the first instance is working.

**Comment by tuupola** [comment]
What have you tried? Can you show the code.

**Comment by blyleven** [comment]
I'm no hero using jQuery, got as fas as: 

`$("#product[]").chained("#category[]");` 

Looping this (nasty) wouldn't do the trick. Just saw some kind of solution in the other issues mentioned earlier. I'll try that out.

**Comment by tuupola** [comment]
Your HTML does not match above. Atleast your example does not have `<select id="product[]">`. Also I believe `[]` are not valid characters in `id`. They are valid in `name` though.

**Comment by blyleven** [comment]
... feeling so stupid right now. Haha. Totally missed out on that one.

**Comment by tuupola** [comment]
You probably can do something like following:

```
<select id="category-1" name="category[]"></select>
<select id="product-1" name="product[]"></select>
<select id="category-2" name="category[]"></select>
<select id="product-2" name="product[]"></select>

$("#product-1").chained("#category-1");
$("#product-2").chained("#category-2");
```

**Comment by blyleven** [comment]
Jes! Works like a charm. Thanks a lot!
