### ISSUE TITLE
is not working inside bootstrap modal , or even a css only modal

### ISSUE THREAD

**Issue by rifkirinaldi** [tuupola/jquery_chained#46]
Hi, is there a way to make this work inside a bootstrap modal ?

The chained also didn't work on a plain css modal , here is the link : 

http://rifkirinaldi.com/chainedselect-issue    ( it is just a simple two select just like in the homepage, the BMW and the Audi )

 it works like charm, but if you click the "Open in CSS only modal" , you could see that the chained select didn't work ..... i find it first on bootstrap modal ( i thought it is because javascript conflict... so i try it on css only modal , but it also didn't work )

**Comment by tuupola** [comment]
It is not valid HTML to have two to have two tags with the same id. Ie. you have two `<select id="mark">` and `<select id="series">`. I would first try fixing that problem.

**Comment by rifkirinaldi** [comment]
oh dear ...i feel so stupid ...thank you Mr. Tuupola !
