### ISSUE TITLE
Duplicate options displaying

### ISSUE THREAD

**Issue by musicmunky** [tuupola/jquery_chained#50]
If you load the following CSV as a chained select you'll get duplicate options - ie, selecting a parent with a similar name to another parent will show the child elements for both parents:  
  
Column1,Column2,Column3,Column4
Test,Option,Test1O1,FourthColumnOpt1
Test,Option,Test2O1,Fourth ColumnOpt1
Test,Option 2,Test3 O2,O24C Col Opt1
Test,Option 2,Test4 O2,024C Col Opt 2
Test TheSecond,Option One,O1 Testing 123,4C Column Opt 1a
Test TheSecond,Option One,O1 Testing 123,4C Column Opt 1b
Test TheSecond,Option One,O1 Testing 456,4C Column Opt 2a
Test TheSecond,Option One,O1 Testing 456,4C Column Opt 2b
Test TheSecond,Option One,O1 Testing 456,4C Column Opt 2c
Test TheSecond,Option Two,O2 FooBar 111,4C O2 O1A
Test TheSecond,Option Two,O2 FooBar 111,4C O2 O1BB
Test TheSecond,Option Two,O2 FooBar 222,4CO2O1A
Test TheSecond,Option Two,O2 FooBar 222,4CO2O1B
Test TheSecond,Option Two,O2 FooBar 222,4CO2O1C
Test TheSecond,Option Two,O2 FooBar 222,4CO2O1D
Test TheSecond,Option Two,O2 FooBar 222,4CO2O1E

It looks like a fix would be to replace the spaces in some places with underscores:
currently_selected_value = currently_selected_value.replace(/\s+/g, "-");

**Comment by tuupola** [comment]
Chained does not have support for loading CSV files. I assume you are loading the CSV in serverside to generate the HTML. If yes then you should generate valid class names in the serverside code. String with a space in it is not a valid class name. Solution is as you said replace the space with character such as - or _.
