### ISSUE TITLE
Chaining to an input

### ISSUE THREAD

**Issue by tanyona** [tuupola/jquery_chained#54]
I know this may be out of scope, but am hoping to get a bit of guidance. I'm currently using chained for selects. Is it possible to have similar functionality for input e.g. after someone types and hits TAB.

**Comment by tanyona** [comment]
I've just tried it out and seen that it works with text inputs - same code as with selects.

**Comment by tuupola** [comment]
Yep, works with other inputs too. Documentation is just lacking...
