### ISSUE TITLE
The branch 2 versions on cdnjs are broken

### ISSUE THREAD

**Issue by fcamp** [tuupola/jquery_chained#56]
Just look at line 122
https://cdnjs.cloudflare.com/ajax/libs/jquery-chained/2.0.0-beta.1/jquery.chained.remote.js

I guess it's an encoding problem

**Comment by tuupola** [comment]
It was some invisible control character. Should be fixed now. CDNJS will take a while to update itself. Thanks for the heads up!

**Comment by tuupola** [comment]
CDNJS seems to be updated.

https://cdnjs.cloudflare.com/ajax/libs/jquery-chained/2.0.0-beta.2/jquery.chained.remote.js
