### ISSUE TITLE
Throws TypeError when data-chained is number

### ISSUE THREAD

**Issue by yeslad** [tuupola/jquery_chained#58]
[This line](https://github.com/tuupola/jquery_chained/blob/2.x/jquery.chained.js#L79) assumes that the value of `data-chained` is a String. However, as per [jQuery docs](https://api.jquery.com/data/) (behavior of [Zepto is similar](http://zeptojs.com/#data)):

> Every attempt is made to convert the string to a JavaScript value (this includes booleans, numbers, objects, arrays, and null). A value is only converted to a number if doing so doesn't change the value's representation. For example, "1E02" and "100.000" are equivalent as numbers (numeric value 100) but converting them would alter their representation so they are left as strings. The string value "100" is converted to the number 100.

Since `Number` does not have a `.split()` method, the script fails at this point if data-chained is a number.

Two solutions are:    
1. Use `.attr('data-chained')` which will always return a string
1. `var data = $(this).data("chained").toString()`

**Comment by dafik** [comment]
Solution nr 2 will not work when data will be null 
since null have no method toString()

better:

const data = $elem.data("chained");
if (data) {
    matches = data.toString().split(" ");
}

**Comment by samuelecarpene** [comment]
Any news about this bug?

**Comment by callumstrubi** [comment]
Sorry I duplicated this bug here:
https://github.com/tuupola/jquery_chained/issues/67
