### ISSUE TITLE
Doesn't work on Internet Explorer 11

### ISSUE THREAD

**Issue by danerrich** [tuupola/jquery_chained#77]
Hello,

i use this plugin in a Web-Application.

However this works perfectly fine in Firefox and Chrome . But if i try it in IE there are no options in my select-box.

Does any of you have the same problem?

(Sorry if this isn't the right place for this issue. I'm new to GitHub...)

**Comment by tuupola** [comment]
Must say I have not used IE myself in ages. Maybe there have been some updates which broke this plugin. Can you see any error messages in the console?

**Comment by danerrich** [comment]
There is just this error on the console in the browser
![error_chained](https://user-images.githubusercontent.com/49186422/55399110-83483880-554a-11e9-9bf9-4bb877e3d57b.PNG)

(i hope you understand the german parts, otherwise let me know)

**Comment by tuupola** [comment]
Where is `selectRemoteChained` defined? It is not part of the plugin code.

**Comment by danerrich** [comment]
I've downloaded your jquery.chained.js. Then i wrote a simple function to createt the chained select:
`function selectRemoteChained(id, parent, url, clear = true){
	id = "#" + id;
	parent = "#" + parent;
	$(id).remoteChained({
		parents: parent,
		url: url,
		clear: clear
	});
}`

**Comment by tuupola** [comment]
The remote version is in different file. It is named `jquery.chained.remote.js`. Maybe that causes the problem.

**Comment by danerrich** [comment]
i took the remote version, i just renamed it.
